# -*- coding: utf-8 -*-
"""Model_Class_Transfer_Learning_MobileNet.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Z1mxFQy7f0hPmcL5biOlghYw7t6gY4E
"""

import torch
from torchvision import models
import torch.nn as nn
import torch.nn.functional as F

# 이미지넷의 1000개  클래스 이미지 1백만 개로 사전학습된 신경망(MobileNet v2)과 가중치 사용
class MobileNet(nn.Module):
  def __init__(self,num_classes,pretrained=True):
    super().__init__()

    # 모델 선언
    self.network = models.mobilenet_v2(pretrained=pretrained)

    # mobilenet 마지막 레이어 수정
    num_ftrs=self.network.classifier[1].in_features
    self.network.classifier[1]=nn.Linear(num_ftrs,num_classes)
    self.classifier=nn.Sequential(nn.Softmax(dim=-1))

  def forward(self,x):
    x=self.network(x)
    x=self.classifier(x)
    return x